{% set name = "ml_ms4alg" %}
{% set repo_owner = "magland" %}
{% set version = "0.2.3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/{{ repo_owner }}/{{ name }}/archive/{{ version }}.tar.gz

build:
  number: 0
  script:
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - python -m pip install --no-deps --ignore-installed .

    # link python package to mountainlab packages dir so processors will be available
    - ML_PACKAGE_DIR=`CONDA_PREFIX=$PREFIX ml-config package_directory`
    - test -n "$ML_PACKAGE_DIR" # error if empty
    - ln -sf $SP_DIR/{{ name }} $ML_PACKAGE_DIR/{{name}}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - mountainlab>=0.15

  run:
    - python
    - numpy
    - h5py
    - mountainlab>=0.15
    - mountainlab_pytools>=0.7.4
    - isosplit5
    - scikit-learn
    
test:
  imports:
    - ml_ms4alg
  commands:
    - ml-list-processors
    - ml-spec ms4alg.sort

about:
  home: https://github.com/magland/ml_ms4alg
  license: Apache Software
  license_family: APACHE
  license_file: ''
  summary: Mountainsort v4 processor plugin for MountainLab
  description: "ml_ms4alg\n\nMountainSort v4\nMountainLab processor library"
  doc_url: ''
  dev_url: ''
